// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CS0fRTk0W0vRhO9qxmlhEagP9pVdgkc',
    appId: '1:737511082315:web:4f683695c22afa78fa40ce',
    messagingSenderId: '737511082315',
    projectId: 'flutter-firebase-remake',
    authDomain: 'flutter-firebase-remake.firebaseapp.com',
    storageBucket: 'flutter-firebase-remake.firebasestorage.app',
    measurementId: 'G-M4PPND86HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDsAMHQnM-FR6kuhJfxXeBGwgVIOVQQIQ',
    appId: '1:737511082315:android:0a43306dec7f0bb7fa40ce',
    messagingSenderId: '737511082315',
    projectId: 'flutter-firebase-remake',
    storageBucket: 'flutter-firebase-remake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7R4eSI7ncTvxoWKqCyzs7_cPER7UmPQ',
    appId: '1:737511082315:ios:a2cabb78013131defa40ce',
    messagingSenderId: '737511082315',
    projectId: 'flutter-firebase-remake',
    storageBucket: 'flutter-firebase-remake.firebasestorage.app',
    iosClientId: '737511082315-p1uk19nvc8q1bgjldh77m7pf396r4gdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekWa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs7R4eSI7ncTvxoWKqCyzs7_cPER7UmPQ',
    appId: '1:737511082315:ios:a2cabb78013131defa40ce',
    messagingSenderId: '737511082315',
    projectId: 'flutter-firebase-remake',
    storageBucket: 'flutter-firebase-remake.firebasestorage.app',
    iosClientId: '737511082315-p1uk19nvc8q1bgjldh77m7pf396r4gdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekWa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CS0fRTk0W0vRhO9qxmlhEagP9pVdgkc',
    appId: '1:737511082315:web:40bd410bae622ffefa40ce',
    messagingSenderId: '737511082315',
    projectId: 'flutter-firebase-remake',
    authDomain: 'flutter-firebase-remake.firebaseapp.com',
    storageBucket: 'flutter-firebase-remake.firebasestorage.app',
    measurementId: 'G-2VK7JSXH53',
  );
}
